kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-from-debug
  namespace: blue
spec:
  podSelector: {}
  ingress:
    - from:
      - podSelector:
          matchLabels:
            run: debug
