kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: http-allow-from-all-default
  namespace: default
spec:
  podSelector:
    matchLabels:
      run: echo-server
  ingress:
  - ports:
    - port: 80
    - port: 443
    from:
    - namespaceSelector: {}
    
